# Generated by Django 3.1 on 2020-11-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
