# Generated by Django 3.1 on 2020-11-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201117_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'file', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключ'),
        ),
    ]
